spring:
  datasource:
    url: jdbc:mysql://192.168.218.128:3306/huanyu?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database: mysql
  jackson:
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
hibernate:
  dialect:
    storage_engine: innodb
server:
  port: 8888